# Generated by Django 5.2 on 2025-05-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # This is an empty migration that does nothing
        # We're using it to synchronize the model state with the database
    ] 