# Generated by Django 5.2 on 2025-05-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250502_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_B2rlDjg.jpg', upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
    ] 